---
# tasks file for roles/nginx

 - name: install nginx
   become: yes
   package:
    name: nginx
    state: installed

 - name: Copy Nginx file
   become: yes
   template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    
 - name: Start Nginx
   become: yes
   service:
    name: nginx
    enabled: yes
    state: started
   notify: restart nginx
