Vagrant.configure("2") do |config|
  config.vm.box = "basebox_4640"

  config.ssh.username = "admin"
  config.ssh.private_key_path = "./files/acit_admin_id_rsa"

  config.vm.define "todoapp" do |todoapp|
    todoapp.vm.hostname = "todoapp.bcit.local"
    todoapp.vm.network "forwarded_port", guest: 80, host: 12080
    todoapp.vm.synced_folder ".", "/vagrant", disabled: true
    
    todoapp.vm.provision :ansible do |ansible|
      ansible.playbook = "todoapp.yml"
      ansible.compatibility_mode = "2.0"
  end
    todoapp.vm.provider "virtualbox" do |vb|
      vb.name = "TODO_4640"
      vb.linked_clone = true
    end
  end
end